# Generated by Django 2.2.7 on 2019-11-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.IntegerField()),
                ('repassword', models.IntegerField()),
            ],
        ),
    ]
